### ISSUE TITLE
考虑放大缩小功能？

### ISSUE THREAD

**Issue by QAbot-zh** [378978764/Snipaste-Android#2]
如题，是否考虑加上一个放大缩小的功能？虽然有裁剪功能，但是有时候忘记先裁剪尺寸太大就只能删掉重来了，如果有放大缩小实用性应该可以大大增强

**Comment by sheng-di** [comment]
我记得当时做的时候是有放大缩小功能的？

<img width="347" alt="image" src="https://github.com/user-attachments/assets/312e37a4-e361-4a5c-84ad-25406b9e5446">

右下角这里可以缩放。

**Comment by QAbot-zh** [comment]
OK，习惯性用双指进行放大缩小了，太棒啦 😆
